Repository rapidsai/cucim, pull requests merged in 2021-04, with the labels that each got.

#4 Update README.md and notebooks
  README.md
  notebooks/Accessing_File_with_GDS.ipynb
  notebooks/Basic_Usage.ipynb
  notebooks/File-access_Experiments_on_TIFF.ipynb
  notebooks/Multi-thread_and_Multi-process_Tests.ipynb
  notebooks/Single-process_Tests.ipynb
  notebooks/Welcome.ipynb
  notebooks/Working_with_Albumentation.ipynb
  notebooks/Working_with_DALI.ipynb
  notebooks/input/README.md
  python/cucim/docs/getting_started/index.md
  run
Labels: doc, non-breaking

#5 Update CUDA versions listed in README
  README.md
Labels: doc, non-breaking

#6 Add additional doc build requirements
  ci/docs/build.sh
Labels: doc, non-breaking

#8 Build and install cucim for docs
  ci/docs/build.sh
Labels: doc, non-breaking

#7 Replace leftover templates in CODEOWNERS [skip ci]
  .github/CODEOWNERS
Labels: bug, non-breaking

#9 Fix a memory leak and update release notes for v0.19.0
  CHANGELOG.md
  README.md
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  python/cucim/CHANGELOG.md
  python/cucim/README.md
  python/cucim/docs/release_notes/index.md
  python/cucim/docs/release_notes/v0.19.0.md
  python/cucim/docs/roadmap/index.md
  python/cucim/src/cucim/__init__.py
Labels: breaking, bug

#12 Update run script for local builds
  3rdparty/LICENSE.cuda
  CMakeLists.txt
  LICENSE-3rdparty.md
  README.md
  ci/cpu/build.sh
  conda/environments/env.yml
  conda/recipes/libcucim/meta.yaml
  cpp/CMakeLists.txt
  cpp/cmake/deps/gds.cmake
  cpp/include/cucim/filesystem/cufile_driver.h
  cpp/plugins/cucim.kit.cuslide/.vscode/settings.json
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/cmake/deps/gds.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo-policies-fix.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo.cmake
  cpp/src/cuimage.cpp
  cpp/src/filesystem/cufile_driver.cpp
  cucim.code-workspace
  gds/CMakeLists.txt
  python/.vscode/settings.json
  python/cucim/CHANGELOG.md
  python/cucim/docs/release_notes/index.md
  python/cucim/docs/release_notes/v0.18.3.md
  python/cucim/docs/release_notes/v0.19.0.md
  python/cucim/src/localtest.py
  python/pybind11/filesystem/filesystem_py.cpp
  python/pybind11/filesystem/filesystem_pydoc.h
  run
Labels: breaking, improvement

#11 HOTFIX Merge of current branch 0.20 to 0.19
  .github/CODEOWNERS
  3rdparty/LICENSE.cuda
  CHANGELOG.md
  CMakeLists.txt
  LICENSE-3rdparty.md
  README.md
  ci/cpu/build.sh
  ci/docs/build.sh
  conda/environments/env.yml
  conda/recipes/libcucim/meta.yaml
  cpp/CMakeLists.txt
  cpp/cmake/deps/gds.cmake
  cpp/include/cucim/filesystem/cufile_driver.h
  cpp/plugins/cucim.kit.cuslide/.vscode/settings.json
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/cmake/deps/gds.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo-policies-fix.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo.cmake
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/src/cuimage.cpp
  cpp/src/filesystem/cufile_driver.cpp
  cucim.code-workspace
  gds/CMakeLists.txt
  notebooks/Accessing_File_with_GDS.ipynb
  notebooks/Basic_Usage.ipynb
  notebooks/File-access_Experiments_on_TIFF.ipynb
  notebooks/Multi-thread_and_Multi-process_Tests.ipynb
  notebooks/Single-process_Tests.ipynb
  notebooks/Welcome.ipynb
  notebooks/Working_with_Albumentation.ipynb
  notebooks/Working_with_DALI.ipynb
  notebooks/input/README.md
  python/.vscode/settings.json
  python/cucim/CHANGELOG.md
  python/cucim/README.md
  python/cucim/docs/getting_started/index.md
  python/cucim/docs/release_notes/index.md
  python/cucim/docs/release_notes/v0.18.3.md
  python/cucim/docs/release_notes/v0.19.0.md
  python/cucim/docs/roadmap/index.md
  python/cucim/src/cucim/__init__.py
  python/cucim/src/localtest.py
  python/pybind11/filesystem/filesystem_py.cpp
  python/pybind11/filesystem/filesystem_pydoc.h
  run
Labels: breaking, improvement

#14 fix scikit-image version skipping in the test suite
  python/cucim/src/cucim/skimage/feature/tests/test_canny.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/metrics/tests/test_simple_metrics.py
  python/cucim/src/cucim/skimage/metrics/tests/test_structural_similarity.py
  python/cucim/src/cucim/skimage/restoration/tests/test_restoration.py
  python/cucim/src/cucim/skimage/util/tests/test_random_noise.py
Labels: bug, non-breaking
