Repository rapidsai/cucim, pull requests merged in 2021-11, with the labels that each got.

#138 update docs theme to pydata-sphinx-theme
  docs/references.css
  docs/requirement.txt
  docs/source/_static/params.css
  docs/source/conf.py
  docs/source/index.rst
Labels: doc, non-breaking

#128 Update initial cpp unittests
  benchmarks/config.h
  benchmarks/main.cpp
  cpp/plugins/cucim.kit.cuslide/benchmarks/config.h
  cpp/plugins/cucim.kit.cuslide/benchmarks/main.cpp
  cpp/plugins/cucim.kit.cuslide/tests/config.h
  cpp/tests/config.h
  cpp/tests/test_read_region.cpp
  cucim.code-workspace
  python/cucim/tests/util/gen_image.py
  test_data/README.md
  test_data/gen_images.sh
Labels: improvement, non-breaking

#129 Add cucim.kit.cumed plugin with skeleton
  CONTRIBUTING.md
  ci/release/update-version.sh
  conda/recipes/libcucim/build.sh
  cpp/CMakeLists.txt
  cpp/include/cucim/config/config.h
  cpp/include/cucim/core/framework.h
  cpp/include/cucim/cuimage.h
  cpp/include/cucim/io/format/image_format.h
  cpp/include/cucim/plugin/image_format.h
  cpp/include/cucim/plugin/plugin_config.h
  cpp/plugins/cucim.kit.cumed/.clang-format
  cpp/plugins/cucim.kit.cumed/.editorconfig
  cpp/plugins/cucim.kit.cumed/.gitignore
  cpp/plugins/cucim.kit.cumed/.idea/.gitignore
  cpp/plugins/cucim.kit.cumed/.idea/.name
  cpp/plugins/cucim.kit.cumed/.idea/codeStyles/Project.xml
  cpp/plugins/cucim.kit.cumed/.idea/codeStyles/codeStyleConfig.xml
  cpp/plugins/cucim.kit.cumed/.idea/cucim.kit.cumed.iml
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/includes/NVIDIA_CMAKE_HEADER.cmake
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/includes/NVIDIA_C_HEADER.h
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/internal/C Header File.h
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/internal/C Source File.c
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/internal/C++ Class Header.h
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/internal/C++ Class.cc
  cpp/plugins/cucim.kit.cumed/.idea/fileTemplates/internal/CMakeLists.txt.cmake
  cpp/plugins/cucim.kit.cumed/.idea/misc.xml
  cpp/plugins/cucim.kit.cumed/.idea/vcs.xml
  cpp/plugins/cucim.kit.cumed/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/VERSION
  cpp/plugins/cucim.kit.cumed/benchmarks/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/benchmarks/config.h
  cpp/plugins/cucim.kit.cumed/benchmarks/main.cpp
  cpp/plugins/cucim.kit.cumed/cmake/cucim.kit.cumed-config.cmake.in
  cpp/plugins/cucim.kit.cumed/cmake/deps/catch2.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/cli11.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/fmt.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/googlebenchmark.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/googletest.cmake
  cpp/plugins/cucim.kit.cumed/cmake/modules/CuCIMUtils.cmake
  cpp/plugins/cucim.kit.cumed/cmake/modules/SuperBuildUtils.cmake
  cpp/plugins/cucim.kit.cumed/src/cumed/cumed.cpp
  cpp/plugins/cucim.kit.cumed/src/cumed/cumed.h
  cpp/plugins/cucim.kit.cumed/test_data
  cpp/plugins/cucim.kit.cumed/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/tests/config.h
  cpp/plugins/cucim.kit.cumed/tests/main.cpp
  cpp/plugins/cucim.kit.cumed/tests/test_basic.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/cuslide.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/tiff.cpp
  cpp/src/config/config.cpp
  cpp/src/core/cucim_framework.cpp
  cpp/src/core/cucim_framework.h
  cpp/src/core/cucim_plugin.cpp
  cpp/src/core/framework.cpp
  cpp/src/cuimage.cpp
  cpp/src/io/format/image_format.cpp
  cpp/src/plugin/image_format.cpp
  cpp/src/plugin/plugin_config.cpp
  run
Labels: improvement, non-breaking

#148 Build with NumPy 1.17
  conda/recipes/cucim/meta.yaml
Labels: bug, non-breaking

#156 Fix Changelog Merge Conflicts for `branch-21.12`
  CHANGELOG.md
Labels: improvement, non-breaking

#158 Fix a segmentation fault due to unloaded libcufile
  cpp/src/filesystem/cufile_driver.cpp
  gds/include/cufile_stub.h
  gds/src/cufile_stub.cpp
Labels: bug, non-breaking

#141 Support Aperio SVS with CPU LZW and jpeg2k decoder
  LICENSE-3rdparty.md
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libopenjpeg.cmake
  cpp/plugins/cucim.kit.cuslide/src/cuslide/cuslide.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg/libjpeg_turbo.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg/libjpeg_turbo.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/color_conversion.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/color_conversion.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/color_table.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/gen_color_table.py
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/libopenjpeg.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/libopenjpeg.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/lzw/lzw.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/lzw/lzw.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/lzw/lzw_libtiff.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/lzw/lzw_libtiff.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/tiff.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/tiff.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/types.h
Labels: feature request, non-breaking

#142 Update change log for v21.10.01
  ci/release/update-version.sh
  notebooks/Accessing_File_with_GDS.ipynb
  python/cucim/CHANGELOG.md
  python/cucim/README.md
Labels: doc, non-breaking

#147 Add Jupyter notebook for SVS Support
  experiments/Supporting_Aperio_SVS_Format/benchmark.py
  experiments/Using_Cache/benchmark.py
  notebooks/Multi-thread_and_Multi-process_Tests.ipynb
  notebooks/Supporting_Aperio_SVS_Format.ipynb
  notebooks/Using_Cache.ipynb
  notebooks/Welcome.ipynb
Labels: doc, non-breaking

#125 Optimize zoom out implementation with separate padding kernel
  python/cucim/src/cucim/core/operations/intensity/kernel/cuda_kernel_source.py
  python/cucim/src/cucim/core/operations/intensity/tests/test_rand_zoom.py
  python/cucim/src/cucim/core/operations/intensity/tests/test_zoom.py
  python/cucim/src/cucim/core/operations/intensity/tests/zoomout_padded.png
  python/cucim/src/cucim/core/operations/intensity/zoom.py
Labels: improvement, non-breaking

#164 Update `conda` recipes for Enhanced Compatibility effort
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#145 Fix thread contention in Cache
  cpp/include/cucim/cache/image_cache_config.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
Labels: bug, non-breaking
