Repository rapidsai/cucim, pull requests merged in 2021-07, with the labels that each got.

#66 Fix a typo in cache document
  notebooks/Using_Cache.ipynb
Labels: doc, non-breaking

#73 Pin `isort` hook to 5.6.4
  .pre-commit-config.yaml
Labels: feature request, non-breaking

#75 Use more descriptive ElementwiseKernel names in cucim.skimage
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/measure/_label_kernels.py
  python/cucim/src/cucim/skimage/util/_map_array.py
Labels: improvement, non-breaking

#65 Fix missing array interface for associated_image()
  python/pybind11/cucim_py.cpp
  python/pybind11/cucim_py.h
Labels: bug, non-breaking

#79 Add SciPy 2021 to README
  README.md
Labels: improvement, non-breaking

#72 Remove int-type bug on Windows in skimage.measure.label
  python/cucim/src/cucim/skimage/measure/_label_kernels.py
Labels: bug, non-breaking

#69 ENH Replace gpuci_conda_retry with gpuci_mamba_retry
  ci/gpu/build.sh
Labels: improvement, non-breaking
