Repository rapidsai/cucim, pull requests merged in 2021-12, with the labels that each got.

#171 Do not compile code with nvcc if no CUDA kernel exists
  cpp/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/src/cumed/cumed.cpp
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/src/filesystem/cufile_driver.cpp
Labels: bug, non-breaking

#175 Remove rmm/nvcc dependencies to fix cudaErrorUnsupportedPtxVersion error
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  cpp/CMakeLists.txt
  cpp/cmake/deps/nvtx3.cmake
  cpp/include/cucim/io/device.h
  cpp/include/cucim/memory/memory_manager.h
  cpp/plugins/cucim.kit.cumed/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/benchmarks/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/benchmarks/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/tests/test_read_rawtiff.cpp
  cpp/src/memory/memory_manager.cpp
  cpp/tests/CMakeLists.txt
  cpp/tests/test_cufile.cpp
  examples/cpp/CMakeLists.txt
  gds/CMakeLists.txt
Labels: bug, non-breaking

#177 Load libcufile.so with RTLD_NODELETE flag
  cpp/include/cucim/dynlib/helper.h
  gds/src/cufile_stub.cpp
Labels: bug, non-breaking

#150 Normalize operation
  python/cucim/src/cucim/core/operations/expose/tests/test_expose.py
  python/cucim/src/cucim/core/operations/expose/transform.py
  python/cucim/src/cucim/core/operations/intensity/__init__.py
  python/cucim/src/cucim/core/operations/intensity/kernel/cuda_kernel_source.py
  python/cucim/src/cucim/core/operations/intensity/normalize.py
  python/cucim/src/cucim/core/operations/intensity/tests/normalized.png
  python/cucim/src/cucim/core/operations/intensity/tests/normalized_atan.png
  python/cucim/src/cucim/core/operations/intensity/tests/test_normalize.py
Labels: feature request, non-breaking

#182 PyPI v21.12.00 release
  CHANGELOG.md
  README.md
  python/cucim/CHANGELOG.md
  python/cucim/README.md
Labels: doc, non-breaking

#183 Add missing imports tests
  conda/recipes/cucim/meta.yaml
Labels: improvement, non-breaking
