Repository rapidsai/cucim, pull requests merged in 2021-05, with the labels that each got.

#21 Use normal RAPIDS environment for CI
  ci/cpu/build.sh
  ci/gpu/build.sh
  conda/environments/env.yml
  conda/recipes/cucim/conda_build_config.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/conda_build_config.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#22 ENH Remove progress output on conda packages upload
  ci/cpu/upload_anaconda.sh
Labels: improvement, non-breaking

#19 Check compression method used in the image (#17)
  cpp/plugins/cucim.kit.cuslide/src/cuslide/cuslide.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.h
Labels: breaking, bug

#26 add egg_info section to setup.py for editable installs
  python/cucim/setup.cfg
Labels: improvement, non-breaking

#28 fix isort on CI
  ci/checks/style.sh
  python/cucim/setup.cfg
  python/cucim/src/cucim/__init__.py
  python/cucim/src/cucim/clara/__init__.py
  python/cucim/src/cucim/skimage/_vendored/_internal.py
  python/cucim/src/cucim/skimage/color/tests/test_colorconv.py
  python/cucim/src/cucim/skimage/color/tests/test_delta_e.py
  python/cucim/src/cucim/skimage/filters/__init__.py
  python/cucim/src/cucim/skimage/filters/tests/test_edges.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/morphology/tests/test_reconstruction.py
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/transform/__init__.py
  python/cucim/src/cucim/time.py
Labels: bug, non-breaking

#30 Document editable install of the Python source
  CONTRIBUTING.md
Labels: doc, non-breaking

#29 MAINT: avoid use of deprecated cp.float, cp.int, cp.bool
  python/cucim/src/cucim/skimage/measure/tests/test_ccomp.py
  python/cucim/src/cucim/skimage/measure/tests/test_profile.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/morphology/binary.py
  python/cucim/src/cucim/skimage/restoration/_denoise.py
  python/cucim/src/cucim/skimage/restoration/tests/test_restoration.py
  python/cucim/src/cucim/skimage/segmentation/boundaries.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_join.py
  python/cucim/src/cucim/skimage/transform/integral.py
Labels: bug, non-breaking

#31 Update release script [skip-ci]
  ci/release/update-version.sh
Labels: improvement, non-breaking

#32 Update release script for CalVer scheme
  ci/release/update-version.sh
  cpp/src/cuimage.cpp
  run
  scripts/auditwheel_repair.py
Labels: breaking, improvement

#36 Pass compiler environment variables to conda python build
  conda/recipes/cucim/meta.yaml
Labels: improvement, non-breaking

#39 Update docs build script [skip ci]
  ci/docs/build.sh
Labels: improvement, non-breaking

#40 Update changelog [skip ci]
  CHANGELOG.md
Labels: improvement, non-breaking

#42 Update `update-version.sh` [skip ci]
  ci/release/update-version.sh
Labels: bug, non-breaking
