Repository rapidsai/cucim, pull requests merged in 2022-06, with the labels that each got.

#276 improve efficiency of histogram-based thresholding functions
  python/cucim/src/cucim/skimage/filters/thresholding.py
Labels: improvement, non-breaking, performance

#294 Populate correct channel names for RGBA image
  cpp/plugins/cucim.kit.cuslide/src/cuslide/cuslide.cpp
  python/cucim/tests/unit/clara/test_load_image_metadata.py
Labels: bug, non-breaking

#295 Update to use DLPack v0.6
  cpp/include/cucim/3rdparty/dlpack/dlpack.h
  cpp/include/cucim/3rdparty/dlpack/dlpackcpp.h
  cpp/include/cucim/io/device_type.h
  cpp/plugins/cucim.kit.cumed/src/cumed/cumed.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/tiff.cpp
  cpp/src/cache/image_cache_per_process.cpp
  cpp/src/cuimage.cpp
  cpp/src/io/device_type.cpp
  cpp/src/loader/thread_batch_data_loader.cpp
  cpp/src/memory/memory_manager.cpp
  python/pybind11/cucim_py.cpp
  python/pybind11/io/io_py.cpp
Labels: improvement, non-breaking

#291 Remove plugin-related messages temporarily
  cpp/src/core/cucim_plugin.cpp
Labels: improvement, non-breaking

#289 update outdated links to example data
  notebooks/input/README.md
Labels: doc, non-breaking

#267 add missing `cucim.skimage.segmentation.clear_border` function
  python/cucim/src/cucim/skimage/segmentation/__init__.py
  python/cucim/src/cucim/skimage/segmentation/_clear_border.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_clear_border.py
Labels: feature request, non-breaking

#272 Fix: return object-typed properties as NumPy arrays in `skimage.measure.regionprops_table`
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: improvement, non-breaking

#273 Stain Normalizer (v2)
  3rdparty/LICENSE.StainTools
  LICENSE-3rdparty.md
  python/cucim/src/cucim/core/operations/color/__init__.py
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
  python/cucim/tests/unit/core/test_stain_normalizer.py
Labels: improvement, non-breaking

#274 Enable footprint decomposition for morphology
  python/cucim/src/cucim/skimage/morphology/ball_decompositions.npy
  python/cucim/src/cucim/skimage/morphology/binary.py
  python/cucim/src/cucim/skimage/morphology/disk_decompositions.npy
  python/cucim/src/cucim/skimage/morphology/footprints.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/morphology/tests/test_binary.py
  python/cucim/src/cucim/skimage/morphology/tests/test_footprints.py
  python/cucim/src/cucim/skimage/morphology/tests/test_gray.py
Labels: improvement, non-breaking

#284 Canny: improve performance with Elementwise kernel
  python/cucim/src/cucim/skimage/feature/_canny.py
Labels: improvement, non-breaking, performance

#297 Remove logging from digital pathology transforms
  python/cucim/src/cucim/core/operations/color/jitter.py
  python/cucim/src/cucim/core/operations/expose/transform.py
  python/cucim/src/cucim/core/operations/intensity/normalize.py
  python/cucim/src/cucim/core/operations/intensity/scaling.py
  python/cucim/src/cucim/core/operations/intensity/zoom.py
  python/cucim/src/cucim/core/operations/spatial/rotate_and_flip.py
Labels: improvement, non-breaking

#310 fix RawKernel bug for canny filter when quantiles are used
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/feature/tests/test_canny.py
Labels: bug, non-breaking
