Repository rapidsai/cucim, pull requests merged in 2022-05, with the labels that each got.

#268 Remove unused dependencies in GPU tests job
  ci/gpu/build.sh
Labels: improvement, non-breaking

#280 Use cupy.fuse to improve efficiency hessian_matrix_eigvals
  python/cucim/src/cucim/skimage/feature/corner.py
Labels: improvement, non-breaking, performance

#278 Promote small integer types to single rather than double precision
  python/cucim/src/cucim/skimage/_shared/tests/test_utils.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/color/tests/test_colorconv.py
  python/cucim/src/cucim/skimage/exposure/exposure.py
  python/cucim/src/cucim/skimage/exposure/tests/test_exposure.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/template.py
  python/cucim/src/cucim/skimage/feature/tests/test_template.py
  python/cucim/src/cucim/skimage/filters/_fft_based.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/filters/tests/test_fft_based.py
  python/cucim/src/cucim/skimage/filters/tests/test_ridges.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/metrics/tests/test_structural_similarity.py
  python/cucim/src/cucim/skimage/restoration/tests/test_denoise.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
  python/cucim/src/cucim/skimage/util/dtype.py
Labels: breaking, improvement, performance

#275 Add missing API docs
  docs/requirement.txt
  docs/source/api.rst
  python/cucim/src/cucim/skimage/feature/corner.py
  python/pybind11/cache/cache_pydoc.h
  python/pybind11/cucim_pydoc.h
Labels: doc, non-breaking

#232 Use conda compilers
  conda/recipes/cucim/conda_build_config.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/conda_build_config.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#286 Simplify recipes
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#216 Build packages using mambabuild
  ci/cpu/build.sh
  ci/gpu/build.sh
Labels: improvement, non-breaking
