Repository rapidsai/cucim, pull requests merged in 2022-10, with the labels that each got.

#404 update pypi CHANGELOG.md for releases 22.08.00 and 22.08.01
  python/cucim/CHANGELOG.md
Labels: doc, non-breaking

#415 Merge docs and add links
  README.md
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
  python/cucim/CHANGELOG.md
  python/cucim/README.md
  python/cucim/setup.py
Labels: improvement, non-breaking

#409 Correctly use dtype when computing shared memory requirements of separable convolution
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
Labels: bug, non-breaking

#338 Add cucim.skimage.feature.match_descriptors
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/match.py
  python/cucim/src/cucim/skimage/feature/tests/test_match.py
Labels: feature request, non-breaking

#378 Add benchmarks for scikit-image functions introduced in 22.08
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/run-nv-bench-morphology.sh
  benchmarks/skimage/run-nv-bench-segmentation.sh
Labels: improvement, non-breaking

#420 Forward merge branch-22.10 to branch-22.12
  CHANGELOG.md
  README.md
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/run-nv-bench-morphology.sh
  benchmarks/skimage/run-nv-bench-segmentation.sh
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
  python/cucim/CHANGELOG.md
  python/cucim/README.md
  python/cucim/setup.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/match.py
  python/cucim/src/cucim/skimage/feature/tests/test_match.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
Labels: improvement, non-breaking
