Repository rapidsai/cucim, pull requests merged in 2022-08, with the labels that each got.

#362 Revert "Allow CuPy 11"
  conda/recipes/cucim/meta.yaml
Labels: improvement, non-breaking

#341 Add cucim.skimage.segmentation.expand_labels
  python/cucim/src/cucim/skimage/segmentation/__init__.py
  python/cucim/src/cucim/skimage/segmentation/_expand_labels.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_expand_labels.py
Labels: feature request, non-breaking

#340 Performance optimizations to morphological segmentation functions
  python/cucim/src/cucim/skimage/_shared/_gradient.py
  python/cucim/src/cucim/skimage/feature/_basic_features.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/registration/_optical_flow.py
  python/cucim/src/cucim/skimage/segmentation/morphsnakes.py
Labels: improvement, non-breaking, performance

#327 Protect against obscure divide by zero error in edge case of `normalize_colors_pca`
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
  python/cucim/tests/unit/core/test_stain_normalizer.py
Labels: improvement, non-breaking

#365 create SimilarityTransform using CuPy 9.x-compatible indexing
  python/cucim/src/cucim/skimage/transform/_geometric.py
Labels: bug, non-breaking

#367 add cucim.core.morphology to API docs + other docstring fixes
  docs/source/api.rst
  docs/source/conf.py
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
  python/cucim/src/cucim/core/operations/morphology/_distance_transform.py
Labels: doc, non-breaking

#343 Add segmentation with the Chan-Vese active contours method
  python/cucim/src/cucim/skimage/segmentation/__init__.py
  python/cucim/src/cucim/skimage/segmentation/_chan_vese.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_chan_vese.py
Labels: feature request, non-breaking

#317 Add a fast histogram-based median filter
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/_median_hist.py
  python/cucim/src/cucim/skimage/filters/cuda/histogram_median.cu
  python/cucim/src/cucim/skimage/filters/tests/test_median.py
Labels: improvement, non-breaking, performance

#355 more efficient separable convolution
  benchmarks/skimage/bench_convolve.py
  python/cucim/setup.cfg
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_vendored/_internal.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_interp_kernels.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_interpolation.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_spline_kernel_weights.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_spline_prefilter_core.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_util.py
  python/cucim/src/cucim/skimage/_vendored/_texture.py
  python/cucim/src/cucim/skimage/_vendored/ndimage.py
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/peak.py
  python/cucim/src/cucim/skimage/filters/_gabor.py
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/edges.py
  python/cucim/src/cucim/skimage/filters/tests/test_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/_blur_effect.py
  python/cucim/src/cucim/skimage/measure/profile.py
  python/cucim/src/cucim/skimage/measure/tests/test_blur_effect.py
  python/cucim/src/cucim/skimage/metrics/_structural_similarity.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/binary.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/registration/tests/test_masked_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/restoration/j_invariant.py
  python/cucim/src/cucim/skimage/segmentation/boundaries.py
  python/cucim/src/cucim/skimage/segmentation/morphsnakes.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/transform/_warps.py
Labels: improvement, non-breaking, performance

#342 Add cucim.skimage.morphology.medial_axis
  python/cucim/src/cucim/skimage/morphology/__init__.py
  python/cucim/src/cucim/skimage/morphology/_medial_axis_lookup.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
Labels: feature request, non-breaking

#349 Support resolution and spacing metadata
  cpp/plugins/cucim.kit.cuslide/src/cuslide/cuslide.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/tiff.cpp
  cpp/src/cuimage.cpp
  python/cucim/requirements-test.txt
  python/cucim/tests/fixtures/testimage.py
  python/cucim/tests/unit/clara/test_load_image_metadata.py
  python/cucim/tests/util/gen_image.py
  python/cucim/tests/util/gen_tiff.py
  run
Labels: improvement, non-breaking

#383 [REVIEW] Defer loading of `custom.js`
  docs/source/conf.py
Labels: doc, non-breaking

#386 Add missing imports of euler_number and perimeter_crofton
  python/cucim/src/cucim/skimage/measure/__init__.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: bug, non-breaking

#388 bump scikit-image requirement to >= 0.19
  conda/environments/env.yml
  conda/recipes/cucim/meta.yaml
Labels: bug, non-breaking

#396 Update README.md
  CHANGELOG.md
  README.md
Labels: doc, non-breaking
