Repository rapidsai/cucim, pull requests merged in 2022-03, with the labels that each got.

#236 Add `.github/ops-bot.yaml` config file [skip ci]
  .github/ops-bot.yaml
Labels: improvement, non-breaking

#226 Update documents for v22.02.00
  CHANGELOG.md
  python/cucim/CHANGELOG.md
  python/cucim/README.md
Labels: doc, non-breaking

#229 Check nullptr of handler in CuFileDriver::close()
  cpp/src/filesystem/cufile_driver.cpp
Labels: bug, non-breaking

#234 Handle file descriptor ownership and update documents for GDS
  cpp/include/cucim/filesystem/cufile_driver.h
  cpp/include/cucim/filesystem/file_handle.h
  cpp/src/filesystem/cufile_driver.cpp
  cpp/src/filesystem/file_handle.cpp
  notebooks/Accessing_File_with_GDS.ipynb
Labels: bug, non-breaking

#208 Apply fixes to skimage.transform scheduled for scikit-image 0.19.2
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/transform/tests/test_geometric.py
Labels: breaking, bug

#249 Update PyPI cuCIM v22.02.01 CHANGELOG.md
  python/cucim/CHANGELOG.md
Labels: doc, non-breaking

#248 Fix wrong dimension in metadata
  cpp/src/cuimage.cpp
  python/cucim/tests/unit/clara/test_tiff_read_region.py
Labels: bug, non-breaking

#246 Expose data type of CuImage object for interoperability with NumPy
  cpp/include/cucim/cuimage.h
  cpp/include/cucim/memory/dlpack.h
  cpp/plugins/cucim.kit.cuslide/benchmarks/main.cpp
  cpp/src/cuimage.cpp
  cpp/tests/test_metadata.cpp
  cpp/tests/test_read_region.cpp
  cucim.code-workspace
  python/cucim/src/cucim/clara/__init__.py
  python/cucim/tests/unit/clara/test_load_image_metadata.py
  python/cucim/tests/unit/clara/test_tiff_read_region.py
  python/pybind11/cucim_py.cpp
  python/pybind11/cucim_pydoc.h
Labels: improvement, non-breaking
