Repository rapidsai/cucim, pull requests merged in 2022-11, with the labels that each got.

#432 Fix rotate behavior for ndim > 2
  python/cucim/src/cucim/skimage/transform/_warps.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
Labels: bug, non-breaking

#423 improved implementation of ridge filters (bug fixes and reduced memory footprint)
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/filters/tests/test_ridges.py
Labels: breaking, improvement

#422 analytical moments computations, support pixel spacings in moments and regionprops
  python/cucim/src/cucim/skimage/measure/_moments.py
  python/cucim/src/cucim/skimage/measure/_moments_analytical.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/_regionprops_utils.py
  python/cucim/src/cucim/skimage/measure/tests/test_moments.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: improvement, non-breaking, performance

#434 Faster `hessian_matrix_*` and `structure_tensor_eigvals` via analytical eigenvalues for the 3D case
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/measure/_moments.py
Labels: improvement, non-breaking, performance

#425 add three segmentation metrics
  benchmarks/skimage/cucim_metrics_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/run-nv-bench-metrics.sh
  python/cucim/src/cucim/skimage/metrics/__init__.py
  python/cucim/src/cucim/skimage/metrics/_adapted_rand_error.py
  python/cucim/src/cucim/skimage/metrics/_contingency_table.py
  python/cucim/src/cucim/skimage/metrics/_variation_of_information.py
  python/cucim/src/cucim/skimage/metrics/tests/test_segmentation_metrics.py
Labels: feature request, non-breaking

#424 Misc updates for consistency with scikit-image 0.20
  python/cucim/src/cucim/skimage/_shared/_dependency_checks.py
  python/cucim/src/cucim/skimage/_shared/_warnings.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/_shared/version_requirements.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/color/delta_e.py
  python/cucim/src/cucim/skimage/color/tests/test_colorlabel.py
  python/cucim/src/cucim/skimage/exposure/_adapthist.py
  python/cucim/src/cucim/skimage/exposure/exposure.py
  python/cucim/src/cucim/skimage/exposure/histogram_matching.py
  python/cucim/src/cucim/skimage/exposure/tests/test_exposure.py
  python/cucim/src/cucim/skimage/exposure/tests/test_histogram_matching.py
  python/cucim/src/cucim/skimage/feature/_basic_features.py
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/peak.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/feature/tests/test_peak.py
  python/cucim/src/cucim/skimage/filters/__init__.py
  python/cucim/src/cucim/skimage/filters/_fft_based.py
  python/cucim/src/cucim/skimage/filters/_rank_order.py
  python/cucim/src/cucim/skimage/filters/_window.py
  python/cucim/src/cucim/skimage/filters/edges.py
  python/cucim/src/cucim/skimage/filters/lpi_filter.py
  python/cucim/src/cucim/skimage/filters/tests/test_edges.py
  python/cucim/src/cucim/skimage/filters/tests/test_fft_based.py
  python/cucim/src/cucim/skimage/filters/tests/test_lpi_filter.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/tests/test_ccomp.py
  python/cucim/src/cucim/skimage/metrics/_structural_similarity.py
  python/cucim/src/cucim/skimage/metrics/simple_metrics.py
  python/cucim/src/cucim/skimage/morphology/grayreconstruct.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/registration/_masked_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/_optical_flow.py
  python/cucim/src/cucim/skimage/registration/_optical_flow_utils.py
  python/cucim/src/cucim/skimage/restoration/_denoise.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/segmentation/_clear_border.py
  python/cucim/src/cucim/skimage/segmentation/_join.py
  python/cucim/src/cucim/skimage/segmentation/morphsnakes.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_chan_vese.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_random_walker.py
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/transform/_warps.py
  python/cucim/src/cucim/skimage/transform/tests/test_geometric.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
  python/cucim/src/cucim/skimage/util/noise.py
Labels: improvement, non-breaking

#444 pin to cmake <3.25 on CI to avoid bug with CUDA+conda during build
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: bug, non-breaking

#413 Add blob feature detectors (blob_dog, blob_log, blob_doh)
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/run-nv-bench-feature.sh
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/_hessian_det_appx.py
  python/cucim/src/cucim/skimage/feature/blob.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/cuda/_hessian_det_appx.cu
  python/cucim/src/cucim/skimage/feature/cuda/blob.cu
  python/cucim/src/cucim/skimage/feature/tests/test_blob.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
Labels: feature request, non-breaking

#433 update incorrect argument and deprecated function for tifffile.TiffWriter
  docker/requirements-claratrain.txt
  docker/requirements-jupyter-dev.txt
  docker/requirements-jupyter.txt
  python/cucim/requirements-test.txt
  python/cucim/src/cucim/clara/converter/tiff.py
  python/cucim/tests/unit/clara/converter/test_converter.py
  run
Labels: bug, non-breaking

#394 Add demo for distance_transform_edt
  examples/python/distance_transform_edt_demo.py
Labels: doc, non-breaking

#443 Support no-compression method in converter
  python/cucim/src/cucim/clara/cli.py
  python/cucim/src/cucim/clara/converter/tiff.py
  python/cucim/tests/unit/clara/converter/test_converter.py
Labels: feature request, non-breaking

#426 use fused kernels to reduce overhead in corner detector implementations
  python/cucim/src/cucim/skimage/feature/corner.py
Labels: improvement, non-breaking, performance

#406 Improve performance of Euclidean distance transform
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
Labels: improvement, non-breaking

#407 Support `sampling` kwarg for `distance_transform_edt` (take pixel/voxel sizes into account)
  python/cucim/src/cucim/core/operations/morphology/_distance_transform.py
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
  python/cucim/src/cucim/core/operations/morphology/cuda/pba_kernels_2d.h
  python/cucim/src/cucim/core/operations/morphology/cuda/pba_kernels_3d.h
  python/cucim/src/cucim/core/operations/morphology/tests/test_distance_transform.py
Labels: improvement, non-breaking

#421 add isotropic binary morphology functions
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/run-nv-bench-morphology.sh
  python/cucim/src/cucim/skimage/morphology/__init__.py
  python/cucim/src/cucim/skimage/morphology/isotropic.py
  python/cucim/src/cucim/skimage/morphology/tests/test_isotropic.py
Labels: feature request, non-breaking

#455 additional minor updates (skimage 0.20)
  python/cucim/src/cucim/core/operations/color/__init__.py
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/_basic_features.py
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/feature/_hessian_det_appx.py
  python/cucim/src/cucim/skimage/feature/blob.py
  python/cucim/src/cucim/skimage/feature/corner.py
  python/cucim/src/cucim/skimage/feature/peak.py
  python/cucim/src/cucim/skimage/feature/tests/test_blob.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/_gabor.py
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/edges.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/filters/tests/test_ridges.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/_blur_effect.py
  python/cucim/src/cucim/skimage/measure/_moments_analytical.py
  python/cucim/src/cucim/skimage/measure/_regionprops_utils.py
  python/cucim/src/cucim/skimage/measure/profile.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/metrics/_contingency_table.py
  python/cucim/src/cucim/skimage/metrics/_structural_similarity.py
  python/cucim/src/cucim/skimage/metrics/_variation_of_information.py
  python/cucim/src/cucim/skimage/metrics/tests/test_segmentation_metrics.py
  python/cucim/src/cucim/skimage/metrics/tests/test_structural_similarity.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/binary.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/restoration/j_invariant.py
  python/cucim/src/cucim/skimage/restoration/tests/test_denoise.py
  python/cucim/src/cucim/skimage/segmentation/boundaries.py
  python/cucim/src/cucim/skimage/segmentation/morphsnakes.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/transform/_warps.py
  python/cucim/src/cucim/skimage/util/dtype.py
  python/cucim/src/cucim/skimage/util/lookfor.py
  python/cucim/src/cucim/skimage/util/tests/test_dtype.py
Labels: improvement, non-breaking

#451 Implement additional deprecations carried out for scikit-image 0.20
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/exposure/histogram_matching.py
  python/cucim/src/cucim/skimage/exposure/tests/test_histogram_matching.py
  python/cucim/src/cucim/skimage/feature/_basic_features.py
  python/cucim/src/cucim/skimage/feature/tests/test_basic_features.py
  python/cucim/src/cucim/skimage/filters/_gaussian.py
  python/cucim/src/cucim/skimage/filters/_unsharp_mask.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
  python/cucim/src/cucim/skimage/filters/tests/test_unsharp_mask.py
  python/cucim/src/cucim/skimage/measure/_label.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/metrics/_structural_similarity.py
  python/cucim/src/cucim/skimage/metrics/tests/test_structural_similarity.py
  python/cucim/src/cucim/skimage/morphology/footprints.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/morphology/tests/test_misc.py
  python/cucim/src/cucim/skimage/restoration/_denoise.py
  python/cucim/src/cucim/skimage/restoration/tests/test_denoise.py
  python/cucim/src/cucim/skimage/restoration/tests/test_j_invariant.py
  python/cucim/src/cucim/skimage/segmentation/_chan_vese.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_random_walker.py
  python/cucim/src/cucim/skimage/transform/_warps.py
  python/cucim/src/cucim/skimage/transform/pyramids.py
  python/cucim/src/cucim/skimage/transform/tests/test_pyramids.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
Labels: breaking, improvement

#452 add whole-slide tiled read/write demos for measuring GPUDirect Storage (GDS) I/O performance
  examples/python/gds_whole_slide/README.md
  examples/python/gds_whole_slide/benchmark_read.py
  examples/python/gds_whole_slide/benchmark_round_trip.py
  examples/python/gds_whole_slide/benchmark_zarr_write.py
  examples/python/gds_whole_slide/benchmark_zarr_write_lz4_via_dask.py
  examples/python/gds_whole_slide/demo_implementation.py
  examples/python/gds_whole_slide/lz4_nvcomp.py
Labels: doc, non-breaking
