Repository rapidsai/cucim, pull requests merged in 2022-07, with the labels that each got.

#344 Forward-merge branch-22.06 to branch-22.08 [skip gpuci]
  CHANGELOG.md
Labels: doc, non-breaking

#339 benchmarks: avoid use of deprecated pandas API
  benchmarks/skimage/cucim_color_bench.py
  benchmarks/skimage/cucim_exposure_bench.py
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/cucim_filters_bench.py
  benchmarks/skimage/cucim_measure_bench.py
  benchmarks/skimage/cucim_metrics_bench.py
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_registration_bench.py
  benchmarks/skimage/cucim_restoration_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/cucim_transform_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_filter_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_fourier_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_interp_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_measurements_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_morphology_bench.py
Labels: improvement, non-breaking

#322 parameterization of `filters` and `features` benchmarks (v2)
  benchmarks/skimage/_image_bench.py
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/cucim_filters_bench.py
  benchmarks/skimage/run-nv-bench-feature.sh
  benchmarks/skimage/run-nv-bench-filters.sh
Labels: improvement, non-breaking

#324 complete parametrization of cucim.skimage benchmarks
  benchmarks/skimage/cucim_color_bench.py
  benchmarks/skimage/cucim_exposure_bench.py
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/cucim_filters_bench.py
  benchmarks/skimage/cucim_measure_bench.py
  benchmarks/skimage/cucim_metrics_bench.py
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_registration_bench.py
  benchmarks/skimage/cucim_restoration_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/cucim_transform_bench.py
  benchmarks/skimage/requirements-bench.txt
  benchmarks/skimage/run-nv-bench-color.sh
  benchmarks/skimage/run-nv-bench-exposure.sh
  benchmarks/skimage/run-nv-bench-feature.sh
  benchmarks/skimage/run-nv-bench-filters.sh
  benchmarks/skimage/run-nv-bench-measure.sh
  benchmarks/skimage/run-nv-bench-metrics.sh
  benchmarks/skimage/run-nv-bench-morphology.sh
  benchmarks/skimage/run-nv-bench-registration.sh
  benchmarks/skimage/run-nv-bench-restoration.sh
  benchmarks/skimage/run-nv-bench-segmentation.sh
  benchmarks/skimage/run-nv-bench-transform.sh
Labels: improvement, non-breaking, performance

#315 Update README.md
  README.md
Labels: doc, non-breaking

#316 Stain extraction: use a less strict condition across channels when thresholding
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
Labels: breaking, bug

#318 Add Euclidean distance transform for images/volumes
  3rdparty/LICENSE.pba+
  LICENSE-3rdparty.md
  python/cucim/src/cucim/core/operations/morphology/__init__.py
  python/cucim/src/cucim/core/operations/morphology/_distance_transform.py
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
  python/cucim/src/cucim/core/operations/morphology/cuda/pba_kernels_2d.h
  python/cucim/src/cucim/core/operations/morphology/cuda/pba_kernels_3d.h
  python/cucim/src/cucim/core/operations/morphology/tests/test_distance_transform.py
Labels: feature request, non-breaking

#328 Reduce memory overhead and improve performance of normalize_colors_pca
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
Labels: improvement, non-breaking, performance

#311 Update PyPI package documentation for v22.06.00
  CHANGELOG.md
  README.md
  python/cucim/CHANGELOG.md
  python/cucim/README.md
Labels: doc, non-breaking

#356 remove unimplemented functions from See Also and fix version numbers in deprecation warnings
  python/cucim/src/cucim/skimage/_shared/tests/test_utils.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/_vendored/signaltools.py
  python/cucim/src/cucim/skimage/exposure/tests/test_exposure.py
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/_label.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/binary.py
  python/cucim/src/cucim/skimage/morphology/footprints.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/grayreconstruct.py
  python/cucim/src/cucim/skimage/morphology/misc.py
  python/cucim/src/cucim/skimage/restoration/_denoise.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/restoration/tests/test_j_invariant.py
  python/cucim/src/cucim/skimage/segmentation/morphsnakes.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/transform/_warps.py
Labels: doc, non-breaking

#357 Allow CuPy 11
  conda/recipes/cucim/meta.yaml
Labels: improvement, non-breaking

#361 Update README.md [skip ci]
  README.md
Labels: doc, non-breaking

#359 Add `__init__.py` in `cucim.core`
  python/cucim/src/cucim/core/__init__.py
Labels: bug, non-breaking

#360 [REVIEW] Fix issues with day & night modes in python docs
  docs/source/_static/params.css
  docs/source/conf.py
Labels: improvement, non-breaking
