Repository rapidsai/cucim, pull requests merged in 2023-11, with the labels that each got.

#621 Standardize on `rng` over `seed` and fix miscellaneous deprecation warnings
  benchmarks/skimage/cucim_metrics_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  python/cucim/src/cucim/core/operations/morphology/_distance_transform.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/data/_binary_blobs.py
  python/cucim/src/cucim/skimage/data/tests/test_data.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/tests/test_edges.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/tests/test_binary.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/restoration/tests/test_restoration.py
  python/cucim/src/cucim/skimage/util/noise.py
  python/cucim/src/cucim/skimage/util/tests/test_random_noise.py
Labels: bug, non-breaking

#619 build wheels on CI
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  CMakeLists.txt
  CONTRIBUTING.md
  VERSION
  ci/build_cpp.sh
  ci/build_python.sh
  ci/build_wheel.sh
  ci/release/update-version.sh
  ci/test_wheel.sh
  ci/wheel_smoke_test.py
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
  cpp/cmake/deps/openslide.cmake
  cpp/plugins/cucim.kit.cumed/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/VERSION
  cpp/plugins/cucim.kit.cuslide/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/VERSION
  cpp/plugins/cucim.kit.cuslide/cmake/deps/openslide.cmake
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg2k/gen_color_table.py
  dependencies.yaml
  python/CMakeLists.txt
  python/cucim/VERSION
  python/cucim/pyproject.toml
  python/cucim/src/cucim/VERSION
  python/cucim/src/cucim/__init__.py
  python/cucim/src/cucim/__init__.pyi
  python/cucim/src/cucim/_version.py
  python/cucim/src/cucim/clara/__init__.py
  python/cucim/src/cucim/skimage/measure/tests/test_blur_effect.py
  python/cucim/src/cucim/skimage/registration/tests/test_masked_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
  python/cucim/tests/unit/clara/converter/test_converter.py
  python/cucim/tests/unit/clara/test_image_cache.py
  python/cucim/tests/unit/clara/test_load_image_metadata.py
  python/cucim/tests/unit/clara/test_tiff_read_region.py
Labels: feature request, non-breaking

#631 carry out removals of previously deprecated functions/kwargs
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/filters/lpi_filter.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/measure/_regionprops_utils.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
Labels: improvement, non-breaking, maintenance

#630 update version string (e.g. for CHANGELOG link) in pyproject.toml
  ci/release/update-version.sh
Labels: bug, non-breaking, maintenance

#632 remove leftover pyproject_.toml file
  python/cucim/pyproject_.toml
Labels: bug, non-breaking, maintenance

#644 Retag wheels to be `cpXY`
  ci/build_wheel.sh
Labels: bug, non-breaking
