Repository rapidsai/cucim, pull requests merged in 2023-04, with the labels that each got.

#516 Fix inefficiency in handling clipping of image range in `resize` and other transforms
  python/cucim/src/cucim/skimage/transform/_warps.py
Labels: breaking, improvement, performance

#517 Binary morphology: omit weights array when possible
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/morphology/footprints.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/isotropic.py
  python/cucim/src/cucim/skimage/morphology/tests/test_binary.py
  python/cucim/src/cucim/skimage/morphology/tests/test_footprints.py
  python/cucim/src/cucim/skimage/morphology/tests/test_gray.py
  python/cucim/src/cucim/skimage/morphology/tests/test_isotropic.py
Labels: improvement, non-breaking, performance

#519 Upgrade dockcross and pybind11
  3rdparty/LICENSE.dockcross
  Dockerfile-cuda110
  Dockerfile-cuda111
  LICENSE-3rdparty.md
  cpp/cmake/deps/pybind11.cmake
  python/cmake/deps/pybind11.cmake
Labels: improvement, non-breaking

#541 Pin `libwebp-base`
  conda/recipes/libcucim/conda_build_config.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#538 Use ARC V2 self-hosted runners for GPU jobs
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#545 add a 20 minute timeout for pytest runs on CI
  ci/test_python.sh
Labels: bug, non-breaking

#546 Remove usage of rapids-get-rapids-version-from-git
  ci/build_docs.sh
  ci/release/update-version.sh
Labels: improvement, non-breaking

#547 Support Python 3.9 build/tests
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: breaking, improvement

#549 Fix `return_error='always'` behavior in phase_cross_correlation
  python/cucim/src/cucim/skimage/registration/_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
Labels: bug, non-breaking

#548 Only load versioned `libcufile`
  cpp/include/cucim/dynlib/helper.h
  gds/src/cufile_stub.cpp
Labels: bug, non-breaking

#550 Revert shared workflows branch
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking
