Repository rapidsai/cucim, pull requests merged in 2023-05, with the labels that each got.

#551 Enable sccache hits from local builds
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#553 Fix doc building via `run build_package`
  notebooks/Accessing_File_with_GDS.ipynb
  notebooks/File-access_Experiments_on_TIFF.ipynb
  notebooks/Supporting_Aperio_SVS_Format.ipynb
  python/cucim/docs/getting_started/index.md
  python/cucim/docs/requirements.txt
  python/cucim/docs/roadmap/index.md
Labels: doc, non-breaking

#552 update changelog for release 23.04.00 and 23.04.01
  CHANGELOG.md
Labels: doc, non-breaking

#558 Update cupy dependency
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#557 Remove libjpeg dependency
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/recipes/libcucim/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#556 Handle space character in ./run download_testdata
  run
Labels: bug, non-breaking

#564 Fix SHA256 check failure in test suite
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
Labels: bug, non-breaking

#563 Allow numpy 1.24.
  python/cucim/docs/requirements.txt
Labels: improvement, non-breaking
