Repository rapidsai/cucim, pull requests merged in 2023-08, with the labels that each got.

#596 Fix ignore_run_exports_from.
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: bug, non-breaking

#599 Remove libwebp-base upper bound.
  conda/recipes/libcucim/conda_build_config.yaml
  conda/recipes/libcucim/meta.yaml
Labels: bug, non-breaking

#601 Postponed the assessment of GPU memory for testing
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: improvement, non-breaking

#605 minor updates to release 23.08 changelog
  CHANGELOG.md
Labels: doc, non-breaking

#606 Use `copy-pr-bot`
  .github/copy-pr-bot.yaml
  .github/ops-bot.yaml
Labels: improvement, non-breaking
