Repository rapidsai/cucim, pull requests merged in 2023-07, with the labels that each got.

#573 Sync cuCIM API with scikit-image 0.21
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/color/__init__.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/color/delta_e.py
  python/cucim/src/cucim/skimage/color/tests/test_colorconv.py
  python/cucim/src/cucim/skimage/exposure/_adapthist.py
  python/cucim/src/cucim/skimage/exposure/exposure.py
  python/cucim/src/cucim/skimage/exposure/tests/test_exposure.py
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/_canny.py
  python/cucim/src/cucim/skimage/feature/tests/test_canny.py
  python/cucim/src/cucim/skimage/filters/__init__.py
  python/cucim/src/cucim/skimage/filters/lpi_filter.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/restoration/__init__.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/restoration/j_invariant.py
  python/cucim/src/cucim/skimage/restoration/tests/test_j_invariant.py
  python/cucim/src/cucim/skimage/restoration/tests/test_restoration.py
  python/cucim/src/cucim/skimage/segmentation/_chan_vese.py
  python/cucim/src/cucim/skimage/segmentation/_join.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_join.py
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/transform/_warps.py
  python/cucim/src/cucim/skimage/transform/tests/test_geometric.py
  python/cucim/src/cucim/skimage/transform/tests/test_warps.py
Labels: breaking, improvement

#578 Use linalg & inline `_get_manders_overlap_coeff`
  python/cucim/src/cucim/skimage/measure/_colocalization.py
Labels: bug, non-breaking

#579 Drop unneeded selector on `libwebp-base`
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#580 Allow scikit-image 0.21.0
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#587 remove checks for versions of scikit-image that are no longer supported
  python/cucim/src/cucim/skimage/_shared/testing.py
  python/cucim/src/cucim/skimage/feature/tests/test_canny.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/metrics/tests/test_simple_metrics.py
  python/cucim/src/cucim/skimage/metrics/tests/test_structural_similarity.py
  python/cucim/src/cucim/skimage/restoration/tests/test_j_invariant.py
  python/cucim/src/cucim/skimage/restoration/tests/test_restoration.py
  python/cucim/src/cucim/skimage/util/tests/test_random_noise.py
Labels: improvement, non-breaking, maintenance

#575 switch from bundled lazy loading code to the public lazy_loader package
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
  python/cucim/MANIFEST.in
  python/cucim/ci/requirements.txt
  python/cucim/setup.py
  python/cucim/src/cucim/__init__.py
  python/cucim/src/cucim/__init__.pyi
  python/cucim/src/cucim/skimage/__init__.py
  python/cucim/src/cucim/skimage/__init__.pyi
  python/cucim/src/cucim/skimage/_shared/lazy.py
  python/cucim/src/cucim/skimage/data/__init__.py
  python/cucim/src/cucim/skimage/data/__init__.pyi
  python/cucim/src/cucim/skimage/filters/__init__.py
  python/cucim/src/cucim/skimage/filters/__init__.pyi
Labels: improvement, non-breaking

#590 Do not use x86_64 GDS binaries for aarch64
  run
Labels: improvement, non-breaking
