Repository rapidsai/cucim, pull requests merged in 2023-10, with the labels that each got.

#613 Use branch-23.12 workflows.
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#614 Update `shared-action-workflows` references
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/release/update-version.sh
Labels: improvement, non-breaking

#615 remove versioneer
  ci/release/update-version.sh
  python/cucim/MANIFEST.in
  python/cucim/setup.cfg
  python/cucim/setup.py
  python/cucim/src/cucim/__init__.pyi
  python/cucim/src/cucim/_version.py
  python/cucim/versioneer.py
Labels: improvement, non-breaking, maintenance

#617 Replace setup.py with pyproject toml
  .pre-commit-config.yaml
  ci/release/update-version.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  conda/recipes/cucim/build.sh
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/setup.cfg
  python/cucim/setup.py
  run
Labels: improvement, non-breaking, maintenance

#618 Update packages (pybind11 and catch2) and do not use nvidia-docker command
  cpp/cmake/deps/catch2.cmake
  cpp/cmake/deps/pybind11.cmake
  cpp/cmake/deps/pybind11_pr4857_4877.patch
  cpp/plugins/cucim.kit.cumed/cmake/deps/catch2.cmake
  cpp/plugins/cucim.kit.cumed/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cumed/tests/main.cpp
  cpp/plugins/cucim.kit.cumed/tests/test_basic.cpp
  cpp/plugins/cucim.kit.cuslide/cmake/deps/catch2.cmake
  cpp/plugins/cucim.kit.cuslide/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/tests/main.cpp
  cpp/plugins/cucim.kit.cuslide/tests/test_philips_tiff.cpp
  cpp/plugins/cucim.kit.cuslide/tests/test_read_rawtiff.cpp
  cpp/plugins/cucim.kit.cuslide/tests/test_read_region.cpp
  cpp/tests/CMakeLists.txt
  cpp/tests/main.cpp
  cpp/tests/test_cufile.cpp
  cpp/tests/test_metadata.cpp
  cpp/tests/test_read_region.cpp
  dockcross-manylinux2014-x64
  notebooks/File-access_Experiments_on_TIFF.ipynb
  python/cmake/deps/pybind11.cmake
  python/cmake/deps/pybind11_pr4857_4877.patch
  python/cucim/docs/getting_started/index.md
  scripts/run-dist
Labels: improvement, non-breaking, maintenance

#620 Fix iterator-related memory issues
  cpp/src/loader/thread_batch_data_loader.cpp
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
  python/cucim/tests/unit/clara/test_tiff_read_region.py
  python/pybind11/cache/cache_py.cpp
  python/pybind11/cucim_py.cpp
Labels: bug, non-breaking

#622 Update linting tool versions and replace isort with ruff
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  CONTRIBUTING.md
  benchmarks/skimage/_image_bench.py
  benchmarks/skimage/cucim_color_bench.py
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/cucim_filters_bench.py
  benchmarks/skimage/cucim_measure_bench.py
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_registration_bench.py
  benchmarks/skimage/cucim_restoration_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/cucim_transform_bench.py
  benchmarks/skimage/cupyx_scipy_ndimage_morphology_bench.py
  examples/python/gds_whole_slide/lz4_nvcomp.py
  experiments/Supporting_Aperio_SVS_Format/benchmark.py
  python/cucim/pyproject.toml
  python/cucim/src/cucim/skimage/segmentation/_chan_vese.py
  python/cucim/src/cucim/skimage/segmentation/tests/test_expand_labels.py
  python/cucim/src/cucim/skimage/transform/_warps.py
  scripts/auditwheel_repair.py
Labels: improvement, non-breaking, maintenance

#623 Improve memory leak check stability in test_read_region_cpu_memleak test
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: improvement, non-breaking, maintenance

#624 fix import order in test case
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: bug, non-breaking
