Repository rapidsai/cucim, pull requests merged in 2023-02, with the labels that each got.

#492 Update `isort` version to 5.12.0
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#491 [REVIEW] Closes #490 -- fixes bug in hue jitter
  python/cucim/src/cucim/core/operations/color/kernel/cuda_kernel_source.py
Labels: bug, non-breaking

#494 apply bug fix to vendored ndimage code
  python/cucim/src/cucim/skimage/_vendored/_ndimage_util.py
Labels: bug, non-breaking

#486 Add disambiguation option to phase_cross_correlation (skimage 0.20 feature)
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/registration/_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
Labels: breaking, feature request

#485 Improve rank filtering performance by removing use of footprint kernel when possible
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/_median_hist.py
  python/cucim/src/cucim/skimage/filters/tests/test_median.py
Labels: improvement, non-breaking, performance

#488 Add colocalization measures
  benchmarks/skimage/cucim_measure_bench.py
  benchmarks/skimage/run-nv-bench-measure.sh
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/_vendored/__init__.py
  python/cucim/src/cucim/skimage/_vendored/_pearsonr.py
  python/cucim/src/cucim/skimage/measure/__init__.py
  python/cucim/src/cucim/skimage/measure/_colocalization.py
  python/cucim/src/cucim/skimage/measure/tests/test_colocalization.py
Labels: feature request, non-breaking

#482 use vendored version of cupy.pad with added performance optimizations
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
  python/cucim/src/cucim/skimage/_vendored/__init__.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_interpolation.py
  python/cucim/src/cucim/skimage/_vendored/pad.py
  python/cucim/src/cucim/skimage/_vendored/pad_elementwise.py
  python/cucim/src/cucim/skimage/exposure/_adapthist.py
  python/cucim/src/cucim/skimage/feature/template.py
  python/cucim/src/cucim/skimage/feature/tests/test_blob.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/_fft_based.py
  python/cucim/src/cucim/skimage/filters/_median_hist.py
  python/cucim/src/cucim/skimage/filters/_sparse.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/_regionprops_utils.py
  python/cucim/src/cucim/skimage/measure/block.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/metrics/simple_metrics.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/segmentation/_chan_vese.py
  python/cucim/src/cucim/skimage/transform/_warps.py
Labels: improvement, non-breaking, performance

#501 Update shared workflow branches
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/release/update-version.sh
Labels: improvement, non-breaking

#497 Move date to build string in `conda` recipe
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: improvement, non-breaking

#508 use cp.around instead of cp.round for CuPy 10.x compatiblity
  python/cucim/src/cucim/core/operations/color/stain_normalizer.py
  python/cucim/src/cucim/skimage/feature/template.py
  python/cucim/src/cucim/skimage/measure/_moments.py
Labels: bug, non-breaking

#510 Update shared workflow branches
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#511 Reduce error handling verbosity in CI tests scripts
  ci/test_python.sh
Labels: improvement, non-breaking

#505 Remove gpuCI scripts.
  ci/checks/style.sh
  ci/cpu/build.sh
  ci/cpu/upload_anaconda.sh
  ci/gpu/build.sh
  ci/local/README.md
  ci/local/build.sh
  conda/recipes/cucim/meta.yaml
Labels: improvement, non-breaking

#506 Fix error in LZ4-compressed Zarr writing demo
  examples/python/gds_whole_slide/benchmark_zarr_write_lz4_via_dask.py
Labels: bug, non-breaking

#515 Fix GHA build workflow
  .github/workflows/build.yaml
Labels: improvement, non-breaking
