Repository rapidsai/cucim, pull requests merged in 2023-12, with the labels that each got.

#648 Fix style issue in `docs/source/conf.py`
  ci/release/update-version.sh
  docs/source/conf.py
Labels: bug, non-breaking

#634 install imagecodecs and openslide-python dependencies so additional tests will run
  ci/test_wheel.sh
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/tests/unit/clara/test_image_cache.py
Labels: improvement, non-breaking, maintenance

#643 Inform `setuptools` that `Extensions` are included
  ci/build_wheel.sh
  python/cucim/LICENSE
  python/cucim/LICENSE-3rdparty.md
  python/cucim/pyproject.toml
  python/cucim/setup.py
Labels: bug, non-breaking

#654 Add 3rd party license file in Conda packages
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
Labels: bug, non-breaking

#669 Update CODEOWNERS
  .github/CODEOWNERS
Labels: improvement, non-breaking

#667 remove .idea folder (CLion IDE configuration)
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/cucim.iml
  .idea/fileTemplates/includes/NVIDIA_CMAKE_HEADER.cmake
  .idea/fileTemplates/includes/NVIDIA_C_HEADER.h
  .idea/fileTemplates/internal/C Header File.h
  .idea/fileTemplates/internal/C Source File.c
  .idea/fileTemplates/internal/C++ Class Header.h
  .idea/fileTemplates/internal/C++ Class.cc
  .idea/fileTemplates/internal/CMakeLists.txt.cmake
  .idea/misc.xml
  .idea/vcs.xml
Labels: improvement, non-breaking, maintenance

#668 remove redundant notebook
  Cache Example.ipynb
Labels: improvement, non-breaking, maintenance

#665 remove various files related to old wheel building mechanism
  .dockerignore
  Dockerfile-cuda110
  Dockerfile-cuda111
  LICENSE-3rdparty.md
  build.sh
  build_docker.sh
  dockcross-manylinux2014-x64
  docker/Dockerfile-claratrain
  docker/Dockerfile-cmake
  docker/Dockerfile-jupyter
  docker/Dockerfile-jupyter-dev
  docker/Dockerfile-jupyter-gds
  docker/Dockerfile-jupyter-gds-dev
  docker/cufile.json
  docker/requirements-claratrain.txt
  docker/requirements-jupyter-dev.txt
  docker/requirements-jupyter.txt
  run
  run_gds.sh
  scripts/auditwheel_repair.py
  scripts/run-dist
Labels: improvement, non-breaking, maintenance

#653 Relax `openslide` pin
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/requirements-test.txt
Labels: improvement, non-breaking, maintenance

#666 Cleanup old ci and docs subfolders and related files under python/cucim
  python/cucim/.appveyor.yml
  python/cucim/.cookiecutterrc
  python/cucim/.gitignore
  python/cucim/.readthedocs.yml
  python/cucim/.travis.yml
  python/cucim/AUTHORS.md
  python/cucim/CONTRIBUTING.md
  python/cucim/MANIFEST.in
  python/cucim/README.md
  python/cucim/VERSION
  python/cucim/ci/appveyor-with-compiler.cmd
  python/cucim/ci/bootstrap.py
  python/cucim/ci/requirements.txt
  python/cucim/ci/templates/.appveyor.yml
  python/cucim/ci/templates/.travis.yml
  python/cucim/docs/_static/css/custom.css
  python/cucim/docs/_static/images/RAPIDS_cuCIM.png
  python/cucim/docs/api_reference/cucim.CuImage.rst
  python/cucim/docs/api_reference/cucim.clara.filesystem.CuFileDriver.rst
  python/cucim/docs/api_reference/cucim.clara.filesystem.rst
  python/cucim/docs/api_reference/cucim.clara.io.Device.rst
  python/cucim/docs/api_reference/cucim.clara.io.rst
  python/cucim/docs/api_reference/cucim.rst
  python/cucim/docs/api_reference/index.md
  python/cucim/docs/conf.py
  python/cucim/docs/development/index.md
  python/cucim/docs/getting_started/index.md
  python/cucim/docs/index.md
  python/cucim/docs/release_notes/index.md
  python/cucim/docs/release_notes/v0.1.0.md
  python/cucim/docs/release_notes/v0.1.1.md
  python/cucim/docs/release_notes/v0.18.0.md
  python/cucim/docs/release_notes/v0.18.1.md
  python/cucim/docs/release_notes/v0.18.2.md
  python/cucim/docs/release_notes/v0.18.3.md
  python/cucim/docs/release_notes/v0.19.0.md
  python/cucim/docs/release_notes/v0.2.0.md
  python/cucim/docs/release_notes/v0.3.0.md
  python/cucim/docs/requirements.txt
  python/cucim/docs/roadmap/index.md
  python/cucim/docs/spelling_wordlist.txt
  python/cucim/docs/user_guide/index.md
  python/cucim/tox.ini
Labels: improvement, non-breaking, maintenance
