Repository rapidsai/cucim, pull requests merged in 2024-01, with the labels that each got.

#671 refactor CUDA versions in dependencies.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#673 Remove usages of rapids-env-update
  ci/build_cpp.sh
  ci/build_python.sh
Labels: improvement, non-breaking

#674 Remove update to symlink
  ci/release/update-version.sh
Labels: bug, non-breaking

#676 Fix CI issues
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
Labels: bug, non-breaking

#680 Fix CI (pt. 2)
  ci/build_wheel.sh
  ci/release/update-version.sh
  ci/test_python.sh
Labels: bug, non-breaking

#683 Consolidate test requirements in `dependencies.yaml`
  dependencies.yaml
  python/cucim/requirements-test.txt
  run
Labels: improvement, non-breaking

#685 Update OpenJPEG to 2.5.0
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libopenjpeg.cmake
Labels: bug, non-breaking

#670 minor updates/fixes for consistency with scikit-image 0.22
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/src/cucim/py.typed
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_vendored/_internal.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/color/tests/test_colorconv.py
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/feature/__init__.pyi
  python/cucim/src/cucim/skimage/feature/peak.py
  python/cucim/src/cucim/skimage/filters/ridges.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/__init__.py
  python/cucim/src/cucim/skimage/measure/__init__.pyi
  python/cucim/src/cucim/skimage/measure/_blur_effect.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/block.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/morphology/__init__.py
  python/cucim/src/cucim/skimage/registration/__init__.py
  python/cucim/src/cucim/skimage/registration/__init__.pyi
  python/cucim/src/cucim/skimage/registration/_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/tests/test_tvl1.py
  python/cucim/src/cucim/skimage/restoration/__init__.py
  python/cucim/src/cucim/skimage/restoration/__init__.pyi
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/restoration/j_invariant.py
  python/cucim/src/cucim/skimage/restoration/tests/test_j_invariant.py
  python/cucim/src/cucim/skimage/segmentation/__init__.py
  python/cucim/src/cucim/skimage/transform/__init__.py
  python/cucim/src/cucim/skimage/transform/__init__.pyi
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/transform/pyramids.py
  python/cucim/src/cucim/skimage/util/dtype.py
Labels: improvement, non-breaking, maintenance

#689 Exclude PyTest 8
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
Labels: bug, non-breaking

#690 Re-run `ci/release/update-version.sh 24.04.00`
  ci/test_python.sh
Labels: bug, non-breaking

#682 add rapids-dependency-file-generator pre-commmit hook
  .pre-commit-config.yaml
Labels: improvement, non-breaking
