Repository rapidsai/cucim, pull requests merged in 2024-04, with the labels that each got.

#716 Use `conda env create --yes` instead of `--force`
  ci/build_docs.sh
  ci/check_style.sh
  ci/test_python.sh
Labels: improvement, non-breaking

#719 Require `click` as a wheel dependency
  dependencies.yaml
  python/cucim/pyproject.toml
Labels: bug, non-breaking

#717 Enable all tests for `arm` jobs
  ci/test_wheel.sh
  ci/wheel_smoke_test.py
Labels: improvement, non-breaking

#713 prevent path conflict
  ci/build_cpp.sh
  ci/build_python.sh
Labels: improvement, non-breaking

#724 removal of deprecated functions/kwargs scheduled for release 24.06
  benchmarks/skimage/cucim_morphology_bench.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
  python/cucim/src/cucim/skimage/registration/_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/registration/tests/test_phase_cross_correlation.py
Labels: improvement, non-breaking, maintenance

#725 Remove code needed to support Python < 3.9 and apply ruff's pyupgrade rules
  python/cucim/pyproject.toml
  python/cucim/src/cucim/_misc.py
  python/cucim/src/cucim/clara/converter/tiff.py
  python/cucim/src/cucim/core/operations/color/jitter.py
  python/cucim/src/cucim/core/operations/intensity/normalize.py
  python/cucim/src/cucim/core/operations/intensity/scaling.py
  python/cucim/src/cucim/core/operations/intensity/zoom.py
  python/cucim/src/cucim/core/operations/morphology/_pba_2d.py
  python/cucim/src/cucim/core/operations/morphology/_pba_3d.py
  python/cucim/src/cucim/skimage/_vendored/_internal.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_interpolation.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_spline_prefilter_core.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_util.py
  python/cucim/src/cucim/skimage/_vendored/_signaltools_core.py
  python/cucim/src/cucim/skimage/_vendored/pad.py
  python/cucim/src/cucim/skimage/_vendored/signaltools.py
  python/cucim/src/cucim/skimage/_vendored/time.py
  python/cucim/src/cucim/skimage/color/colorconv.py
  python/cucim/src/cucim/skimage/exposure/_adapthist.py
  python/cucim/src/cucim/skimage/feature/_hessian_det_appx.py
  python/cucim/src/cucim/skimage/feature/blob.py
  python/cucim/src/cucim/skimage/feature/template.py
  python/cucim/src/cucim/skimage/filters/_median.py
  python/cucim/src/cucim/skimage/filters/_median_hist.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/tests/test_median.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/measure/_label_kernels.py
  python/cucim/src/cucim/skimage/morphology/tests/test_gray.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
  python/cucim/src/cucim/skimage/registration/_optical_flow.py
  python/cucim/src/cucim/skimage/registration/tests/test_masked_phase_cross_correlation.py
  python/cucim/src/cucim/skimage/segmentation/random_walker_segmentation.py
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/util/tests/test_dtype.py
  python/cucim/src/localtest.py
  python/cucim/tests/util/gen_image.py
Labels: improvement, non-breaking, maintenance

#726 Update the test criteria for test_read_random_region_cpu_memleak
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: improvement, non-breaking, maintenance

#733 Use SciPy's KDTree instead of deprecated cKDTree
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/src/cucim/skimage/_shared/coord.py
  python/cucim/src/cucim/skimage/_shared/tests/test_coord.py
  python/cucim/src/cucim/skimage/feature/corner.py
Labels: bug, non-breaking, maintenance
