Repository rapidsai/cucim, pull requests merged in 2024-02, with the labels that each got.

#693 Fix `popd` indent in `run`
  run
Labels: bug, non-breaking

#695 Fix CUDA trove classifiers & update README install instructions
  README.md
  python/cucim/pyproject.toml
Labels: bug, non-breaking

#672 Support CUDA 12.2
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/meta.yaml
  dependencies.yaml
Labels: feature request, non-breaking

#699 Refactor CUDA libraries in dependencies.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#702 target branch-24.04 for GitHub Actions workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#694 Update ops-bot.yaml
  .github/ops-bot.yaml
Labels: improvement, non-breaking

#704 Add support for Python 3.11, require NumPy 1.23+
  benchmarks/skimage/_image_bench.py
  benchmarks/skimage/bench_convolve.py
  benchmarks/skimage/cucim_color_bench.py
  benchmarks/skimage/cucim_exposure_bench.py
  benchmarks/skimage/cucim_feature_bench.py
  benchmarks/skimage/cucim_filters_bench.py
  benchmarks/skimage/cucim_measure_bench.py
  benchmarks/skimage/cucim_metrics_bench.py
  benchmarks/skimage/cucim_morphology_bench.py
  benchmarks/skimage/cucim_registration_bench.py
  benchmarks/skimage/cucim_restoration_bench.py
  benchmarks/skimage/cucim_segmentation_bench.py
  benchmarks/skimage/cucim_transform_bench.py
  ci/wheel_smoke_test.py
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
  examples/python/distance_transform_edt_demo.py
  examples/python/gds_whole_slide/benchmark_round_trip.py
  examples/python/gds_whole_slide/benchmark_zarr_write.py
  examples/python/gds_whole_slide/demo_implementation.py
  examples/python/tiff_image/main.py
  experiments/Supporting_Aperio_SVS_Format/benchmark.py
  experiments/Using_Cache/benchmark.py
Labels: improvement, non-breaking
