Repository rapidsai/cucim, pull requests merged in 2024-10, with the labels that each got.

#785 Do not depends on unused libraries for libtiff
  CONTRIBUTING.md
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/libcucim/meta.yaml
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libtiff.cmake
  dependencies.yaml
Labels: improvement, non-breaking, maintenance

#786 Deprecations: carry out removals scheduled for release 24.12
  python/cucim/src/cucim/skimage/__init__.py
  python/cucim/src/cucim/skimage/data/_binary_blobs.py
  python/cucim/src/cucim/skimage/data/tests/test_data.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/util/lookfor.py
  python/cucim/src/cucim/skimage/util/noise.py
  python/cucim/src/cucim/skimage/util/tests/test_random_noise.py
Labels: breaking, improvement, maintenance

#791 make conda installs in CI stricter
  ci/build_docs.sh
Labels: improvement, non-breaking

#792 build wheels without build isolation, print sccache stats in builds
  .pre-commit-config.yaml
  ci/build_cpp.sh
  ci/build_python.sh
  ci/build_wheel.sh
  dependencies.yaml
Labels: improvement, non-breaking
