Repository rapidsai/cucim, pull requests merged in 2024-09, with the labels that each got.

#770 Disable custom 2D separable filtering kernels on windows
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/filters/tests/test_separable_filtering.py
Labels: bug, non-breaking

#773 Add support for Python 3.12
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#777 Use cupy to measure memory leak
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: bug, non-breaking

#780 Use CI workflow branch 'branch-24.10' again
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#782 Fix a couple of performance issues in `peak_local_max` (improve performance of blob detectors and `corner_peaks`)
  python/cucim/src/cucim/skimage/_shared/coord.py
  python/cucim/src/cucim/skimage/feature/peak.py
Labels: improvement, non-breaking, performance

#781 update vendored CUDA includes to match CuPy >= 13.3
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
Labels: improvement, non-breaking
