Repository rapidsai/cucim, pull requests merged in 2025-07, with the labels that each got.

#901 Fix test failures due to deprecated Pillow Image.fromarray 'mode' parameter
  python/cucim/src/cucim/core/operations/color/tests/test_color_jitter.py
  python/cucim/src/cucim/core/operations/intensity/tests/test_normalize.py
  python/cucim/src/cucim/core/operations/intensity/tests/test_scaling.py
  python/cucim/src/cucim/core/operations/intensity/tests/test_zoom.py
  python/cucim/src/cucim/core/operations/spatial/tests/test_flip.py
  python/cucim/src/cucim/core/operations/spatial/tests/test_rotate90.py
Labels: bug, non-breaking

#897 add docs on CI workflow inputs
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: doc, non-breaking

#903 Drop CUDA 11 from CI Scripts
  ci/test_wheel.sh
Labels: improvement, non-breaking

#907 Drop unused variable `CUDA_MAJOR_VERSION`
  ci/test_wheel.sh
Labels: bug, non-breaking

#898 Enhance GPU memory leak test with unified memory check and increased thresholds
  python/cucim/tests/performance/clara/test_read_region_memory_usage.py
Labels: improvement, non-breaking, maintenance
