Repository rapidsai/cucim, pull requests merged in 2025-01, with the labels that each got.

#809 Improve performance of color distance calculations by kernel fusion
  benchmarks/skimage/cucim_color_bench.py
  benchmarks/skimage/run-nv-bench-color.sh
  python/cucim/src/cucim/skimage/color/delta_e.py
  python/cucim/src/cucim/skimage/color/tests/test_delta_e.py
Labels: improvement, non-breaking

#808 CuPy 14.0 compatibility
  python/cucim/src/cucim/skimage/_shared/compat.py
  python/cucim/src/cucim/skimage/feature/tests/test_corner.py
  python/cucim/src/cucim/skimage/filters/thresholding.py
  python/cucim/src/cucim/skimage/registration/_optical_flow.py
  python/cucim/src/cucim/skimage/transform/integral.py
Labels: bug, non-breaking

#812 Fix primitives benchmark code
  benchmarks/primitives.cpp
Labels: bug, non-breaking

#806 Incorporate upstream changes from scikit-image 0.25
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
  python/cucim/src/cucim/__init__.py
  python/cucim/src/cucim/skimage/__init__.py
  python/cucim/src/cucim/skimage/__init__.pyi
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_shared/testing.py
  python/cucim/src/cucim/skimage/_shared/tests/test_utils.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/color/__init__.py
  python/cucim/src/cucim/skimage/data/__init__.py
  python/cucim/src/cucim/skimage/exposure/__init__.py
  python/cucim/src/cucim/skimage/feature/__init__.py
  python/cucim/src/cucim/skimage/filters/__init__.py
  python/cucim/src/cucim/skimage/filters/_gabor.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
  python/cucim/src/cucim/skimage/measure/__init__.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/metrics/__init__.py
  python/cucim/src/cucim/skimage/metrics/_contingency_table.py
  python/cucim/src/cucim/skimage/morphology/__init__.py
  python/cucim/src/cucim/skimage/morphology/_skeletonize.py
  python/cucim/src/cucim/skimage/morphology/footprints.py
  python/cucim/src/cucim/skimage/morphology/gray.py
  python/cucim/src/cucim/skimage/morphology/tests/test_binary.py
  python/cucim/src/cucim/skimage/morphology/tests/test_footprints.py
  python/cucim/src/cucim/skimage/morphology/tests/test_gray.py
  python/cucim/src/cucim/skimage/morphology/tests/test_skeletonize.py
  python/cucim/src/cucim/skimage/registration/__init__.py
  python/cucim/src/cucim/skimage/registration/_optical_flow.py
  python/cucim/src/cucim/skimage/registration/_optical_flow_utils.py
  python/cucim/src/cucim/skimage/restoration/__init__.py
  python/cucim/src/cucim/skimage/restoration/deconvolution.py
  python/cucim/src/cucim/skimage/segmentation/__init__.py
  python/cucim/src/cucim/skimage/segmentation/_join.py
  python/cucim/src/cucim/skimage/segmentation/boundaries.py
  python/cucim/src/cucim/skimage/transform/__init__.py
  python/cucim/src/cucim/skimage/transform/_geometric.py
  python/cucim/src/cucim/skimage/util/__init__.py
  python/cucim/src/cucim/skimage/util/_map_array.py
Labels: improvement, non-breaking, maintenance

#811 Use GCC 13 in CUDA 12 conda builds.
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/cucim/conda_build_config.yaml
  conda/recipes/cucim/meta.yaml
  conda/recipes/libcucim/conda_build_config.yaml
  conda/recipes/libcucim/meta.yaml
  cpp/src/concurrent/threadpool.cpp
  dependencies.yaml
Labels: improvement, non-breaking

#815 Build and test with CUDA 12.8.0
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#814 Add shellcheck to pre-commit and fix warnings
  .pre-commit-config.yaml
  ci/build_docs.sh
  ci/build_wheel.sh
  ci/release/update-version.sh
  ci/test_wheel.sh
  ci/validate_wheel.sh
Labels: improvement, non-breaking

#818 Revert CUDA 12.8 shared workflow branch changes
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#819 Forward-merge branch-25.02 to branch-25.04
  .pre-commit-config.yaml
  ci/build_docs.sh
  ci/build_wheel.sh
  ci/release/update-version.sh
  ci/test_wheel.sh
  ci/validate_wheel.sh
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#817 Migrate to NVKS for amd64 CI runners
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking
