Repository rapidsai/cucim, pull requests merged in 2025-02, with the labels that each got.

#820 raise setuptools floor to 61.0.0, sphinx floor to 8.0.0, other small dependencies cleanup
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/recipes/cucim/meta.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
Labels: improvement, non-breaking

#813 Update vendored ndimage code with axes support
  python/cucim/src/cucim/skimage/_shared/filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_filters_core.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_interpolation.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
  python/cucim/src/cucim/skimage/_vendored/_ndimage_util.py
  python/cucim/src/cucim/skimage/_vendored/ndimage.py
  python/cucim/src/cucim/skimage/_vendored/tests/test_morphology.py
  python/cucim/src/cucim/skimage/filters/_separable_filtering.py
  python/cucim/src/cucim/skimage/filters/tests/test_gaussian.py
Labels: improvement, non-breaking

#824 Use `rapids-pip-retry` in CI jobs that might need retries
  ci/build_wheel.sh
  ci/test_wheel.sh
Labels: improvement, non-breaking

#822 add telemetry
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#826 Use shared-workflows branch-25.04
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#833 Create Conda CI test env in one step
  ci/release/update-version.sh
  ci/test_python.sh
  dependencies.yaml
Labels: improvement, non-breaking

#835 Consolidate more Conda solves in CI
  ci/build_docs.sh
  dependencies.yaml
Labels: improvement, non-breaking

#823 Add cuCIM pronunciation to README
  README.md
Labels: doc, non-breaking

#840 require sphinx<8.2.0
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  python/cucim/pyproject.toml
Labels: improvement, non-breaking

#841 Use conda-build instead of conda-mambabuild
  ci/build_cpp.sh
  ci/build_python.sh
Labels: improvement, non-breaking

#837 vendor CUDA-accelerated `find objects`
  python/cucim/src/cucim/skimage/_vendored/_ndimage_measurements.py
  python/cucim/src/cucim/skimage/_vendored/ndimage.py
  python/cucim/src/cucim/skimage/feature/peak.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
Labels: improvement, non-breaking

#831 Add build_type input to `test.yaml`
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#839 Improve performance of `label2rgb`
  benchmarks/skimage/cucim_color_bench.py
  python/cucim/src/cucim/skimage/color/colorlabel.py
Labels: improvement, non-breaking, performance

#838 add utility for memory efficient maximum pairwise distance computation with GPU support
  python/cucim/src/cucim/skimage/_shared/distance.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: improvement, non-breaking

#836 update vendored binary morphology code
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
Labels: improvement, non-breaking

#828 Implement `convex_hull_image` and `convex_hull_object`
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/morphology/__init__.py
  python/cucim/src/cucim/skimage/morphology/convex_hull.py
  python/cucim/src/cucim/skimage/morphology/tests/test_convex_hull.py
Labels: improvement, non-breaking, performance
