Repository rapidsai/cucim, pull requests merged in 2025-04, with the labels that each got.

#858 Update various library versions to meet the minimum required CMake version (>= 3.5) for compatibility with CMake 3.30.4.
  cpp/cmake/deps/cli11.cmake
  cpp/cmake/deps/fmt.cmake
  cpp/cmake/deps/googletest.cmake
  cpp/cmake/deps/json.cmake
  cpp/cmake/deps/libcuckoo.patch
  cpp/include/cucim/util/cuda.h
  cpp/plugins/cucim.kit.cumed/cmake/deps/cli11.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/fmt.cmake
  cpp/plugins/cucim.kit.cumed/cmake/deps/googletest.cmake
  cpp/plugins/cucim.kit.cumed/tests/CMakeLists.txt
  cpp/plugins/cucim.kit.cuslide/cmake/deps/cli11.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/fmt.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/googletest.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/json.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libjpeg-turbo.patch
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libopenjpeg.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libopenjpeg.patch
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libtiff.cmake
  cpp/plugins/cucim.kit.cuslide/cmake/deps/libtiff.patch
  cpp/plugins/cucim.kit.cuslide/cmake/deps/pugixml.cmake
  cpp/plugins/cucim.kit.cuslide/src/cuslide/jpeg/libjpeg_turbo.cpp
  cpp/plugins/cucim.kit.cuslide/src/cuslide/lzw/lzw_libtiff.h
  cpp/plugins/cucim.kit.cuslide/src/cuslide/tiff/ifd.cpp
  cpp/plugins/cucim.kit.cuslide/tests/CMakeLists.txt
  cpp/src/cache/image_cache_per_process.cpp
  cpp/src/cuimage.cpp
  cpp/src/loader/thread_batch_data_loader.cpp
  cpp/tests/CMakeLists.txt
  python/cmake/deps/fmt.cmake
  python/cmake/deps/json.cmake
  python/cmake/deps/pybind11_json.cmake
Labels: improvement, non-breaking, maintenance

#849 Consistently raise error on non-CuPy input to regionprops functions
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: bug, non-breaking

#851 avoid potential CUDA out of bounds memory access in test case
  python/cucim/src/cucim/skimage/filters/tests/test_thresholding.py
Labels: bug, non-breaking

#842 update vendored binary_fill_holes
  python/cucim/src/cucim/skimage/_vendored/_ndimage_morphology.py
Labels: bug, non-breaking

#843 Region Properties Performance Overhaul - Part 1: Basic Properties
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_basic_kernels.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_utils.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops_gpu_kernels.py
  python/cucim/src/cucim/skimage/morphology/convex_hull.py
Labels: improvement, non-breaking, performance

#844 Region Properties Performance Overhaul - Part 2: Intensity Image Properties
  python/cucim/pyproject.toml
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_intensity_kernels.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_utils.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops_gpu_kernels.py
Labels: improvement, non-breaking, performance

#845 Region Properties Performance Overhaul - Part 3: Convex Image Properties
  python/cucim/src/cucim/skimage/_shared/distance.py
  python/cucim/src/cucim/skimage/_shared/utils.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_basic_kernels.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_convex.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops_gpu_kernels.py
Labels: improvement, non-breaking, performance

#846 Region Properties Performance Overhaul - Part 4: Moment-Based Properties
  python/cucim/src/cucim/skimage/measure/_moments_analytical.py
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_moments_kernels.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops_gpu_kernels.py
Labels: improvement, non-breaking, performance

#847 Region Properties Performance Overhaul - Part 5: Perimeter and Euler Characteristic
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_misc_kernels.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu_utils.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops_gpu_kernels.py
Labels: improvement, non-breaking, performance

#848 Region Properties Performance Overhaul - Part 6: Public API (regionprops_table)
  python/cucim/src/cucim/skimage/measure/_regionprops.py
  python/cucim/src/cucim/skimage/measure/_regionprops_gpu.py
  python/cucim/src/cucim/skimage/measure/tests/test_regionprops.py
Labels: improvement, non-breaking, performance

#870 Download build artifacts from GitHub for CI
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/build_docs.sh
  ci/build_python.sh
  ci/test_python.sh
  ci/test_wheel.sh
Labels: improvement, non-breaking
